export const RESPONSE_SUCCESS_MESSAGE = {
    8001: "success",
    8002: "mail sent successfully to register user",
    8003: "user registerd successfully",
    8004: "user logged in successfully",
    8005: "user logged out successfully",
    8006: "user found",
    8007: "problem created successfully",
    8008: "problems fetched successfully",
    8009: "problem fetched successfully",
    8010: "problem updated successfully",
    8011: "problem deleted successfully",
    8012: "problem executed successfully",
    8013: "user submissions fetched successfully",
    8014: "problem submissions for user fetched successfully",
    8015: "problem submissions fetched successfully",
    8016: "problems solved by user fetched successfully",
    8017: "playlist created successfully",
    8018: "all playlist for user fetched successfully",
    8019: "playlist fetched successfully",
    8020: "problems added to the playlist",
    8021: "playlist deleted successfully",
    8022: "problem(s) removed successfully",
    8023: "playlist details updated successfully",
    8024: "problems from playlist for a user fetched successfully",
    8025: "created problems fetched successfully",
};

export const RESPONSE_ERROR_MESSAGE = {
    1001: "failure",
    1002: "Request body validation error",
    1003: "User already exists",
    1004: "Failed to send Email",
    1005: "User does not exists",
    1006: "Invalid Credentials",
    1007: "Token not available",
    1008: "Token Expired",
    1009: "User not authorised",
    1010: "Language not found",
    1011: "Error in Sample Solution",
    1012: "Problems not found",
    1013: "Problem not found",
    1014: "User not found",
    1015: "Request params validation error",
    1016: "Request query validation error",
    1017: "Problem to be deleted not found",
    1018: "Error creating playlist",
    1019: "Playlist not found",
    1020: "Failed to update playlist details",
};

export const COOKIE_OPTIONS = {
    httpOnly: true,
    sameSite: "strict",
    secure: process.env.NODE_ENV !== "dev",
    maxAge: 1000 * 60 * 60 * 24 * 7, // 7 days
};
