export const RESPONSE_SUCCESS_MESSAGE = {
    8001: "success",
    8002: "mail sent successfully to register user",
    8003: "user registerd successfully",
    8004: "user logged in successfully",
    8005: "user logged out successfully",
    8006: "user found",
    8007: "problem created successfully",
    8008: "problems fetched successfully",
    8009: "problem fetched successfully",
    8010: "problem updated successfully",
    8011: "problem deleted successfully",
    8012: "problem submitted successfully",
    8013: "user submissions fetched successfully",
    8014: "problem submissions for user fetched successfully",
    8015: "problem submissions fetched successfully",
    8016: "problems solved by user fetched successfully",
    8017: "playlist created successfully",
    8018: "all playlist for user fetched successfully",
    8019: "playlist fetched successfully",
    8020: "problems added to the playlist",
    8021: "playlist deleted successfully",
    8022: "problem(s) removed successfully",
    8023: "playlist details updated successfully",
    8024: "problems from playlist for a user fetched successfully",
    8025: "created problems fetched successfully",
    8026: "tags info fetched successfully",
    8027: "password updated successfully",
    8028: "tags updated successfully",
    8029: "forgot password initiated",
    8030: "password resset for user",
    8031: "room created successfully",
    8032: "room deleted successfully",
    8033: "room updated successfully",
    8034: "room code generated successfully",
    8035: "created room details fetched successfully",
    8036: "user room details fetched successfully",
    8037: "user rejoined room successfully",
    8038: "user joined room successfully",
    8039: "user rooms fetched successfully",
    8040: "room user details featched successfully",
    8041: "room settings updated successfully",
    8042: "room members fetched successfully",
    8043: "playlist basic details fethced",
    8044: "room members fetched for admin successfully",
    8045: "room member details updated successfully",
};

export const RESPONSE_ERROR_MESSAGE = {
    1001: "failure",
    1002: "Request body validation error",
    1003: "User already exists",
    1004: "Failed to send Email",
    1005: "User does not exists",
    1006: "Invalid Credentials",
    1007: "Token not available",
    1008: "Token Expired",
    1009: "User not authorised",
    1010: "Language not found",
    1011: "Error in Sample Solution",
    1012: "Problems not found",
    1013: "Problem not found",
    1014: "User not found",
    1015: "Request params validation error",
    1016: "Request query validation error",
    1017: "Problem to be deleted not found",
    1018: "Error creating playlist",
    1019: "Playlist not found",
    1020: "Failed to update playlist details",
    1021: "Failed to update password",
    1022: "Failed to update tags",
    1023: "Failed to reset Password",
    1024: "Failed to send mail",
    1025: "Failed to reset Password",
    1026: "Failed to reset Password",
    1027: "Failed to reset Password",
    1028: "Unauthorized to create Room",
    1029: "Room does not exist",
    1030: "Error creating Room",
    1031: "Error deleting Room",
    1032: "Error updating Room",
    1033: "Error updating Room Code",
    1034: "Failed to generate Room Code",
    1035: "Error getting Created Room details",
    1036: "Error getting user Rooms",
    1037: "Error joining room",
    1038: "User Already in room",
    1039: "User banned from the room",
    1040: "Error leaving room",
    1041: "User is not active member of this room",
    1042: "Error fetching Room Member details",
    1043: "Failed to get Room Member detais",
    1044: "Error updating open close status of room",
    1045: "Failed updating open close status of room",
    1046: "Error getting Room Members",
    1047: "No permission to fetch members",
    1048: "Failed to get room members",
    1049: "Error deleting member from room",
    1050: "Student Not Found in room",
    1051: "Error getting Playlist basic details",
    1052: "Failed to get Playlist basic details",
    1053: "User not authorized or found to search playlist basic information",
    1056: "Error in sample solution of edited problem",
    1057: "User not authorized to update problem",
    1058: "User not authorized to for admin get members",
    1059: "Failed to get room members for admin",
    1060: "Error getting Room Members for Admin",
    1061: "Error updating User Permission",
    1062: "User not authorized to change permissions",
    1063: "Failed to update user permissions",
    1064: "User not a teacher in given room",
    1065: "Playlist in that room not found",
    1066: "Error deleting playlist",
};

export const COOKIE_OPTIONS = {
    httpOnly: true,
    sameSite: "strict",
    secure: process.env.NODE_ENV !== "dev",
    maxAge: 1000 * 60 * 60 * 24 * 7, // 7 days
};
